<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8">
		<title>Monteria Opina</title>
		<link rel="stylesheet" href="resource/css/bootstrap.min.css">
        <link rel="stylesheet" href="resource/css/estilos.css">
		<link rel="stylesheet" href="resource/js/jquery-ui/jquery-ui.min.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
		
        <script src="resource/js/jquery-2.2.3.min.js"></script>
          <script src="resource/js/jquery-3.1.1.min.js" type="text/javascript" charset="utf-8" ></script>
          <script src="resource/js/bootstrap.min.js" type="text/javascript" charset="utf-8" ></script>

	</head>

	<body>
		<div class="container">

	
			<div class="row">
				<div class="col-md-4"></div>
				<div class="col-md-4">
					<img src="resource/img/logo.png"  class="img-responsive">
				</div>
				<div class="col-md-4"></div>
			</div>
			<div class="row">
				<nav  class="navbar navbar-custom" role="navigation" role="navigation">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
							<span class="sr-only">Cambiar Navegacion</span>
						</button>
						<a href="#" class="navbar-brand">MonteriaOpina</a>
					</div>
					<div class="collapse navbar-collapse navbar-ex1-collapse">
						<ul class="nav navbar-nav">
							<li>
								<a  href="?c=Usuario&a=HomeEdil">
									<span class="glyphicon glyphicon-home"></span>
									<span>Home</span>
								</a>
							</li>
							<li>
								<a href="?c=Proyecto&a=misProyectos">
									<span class="glyphicon glyphicon-user"></span>
									<i class="fa fa-file-pdf-o"></i>
									<span>Mis Proyectos</span>
								</a>
							</li>

							<li>
								<a href="?c=Proyecto&a=Datos">
									<span class="glyphicon glyphicon-user"></span>
									<i class="fa fa-file-pdf-o"></i>
									<span>Consultar Datos</span>
								</a>
							</li>

							<li>
								<a href="?c=Proyecto&a=Grafica">
									<span class="glyphicon glyphicon-user"></span>
									<i class="fa fa-file-pdf-o"></i>
									<span>Grafica de Datos</span>
								</a>
							</li>

							
							
						
							<li>
								<a href="?c=Usuario&a=Logout">
									<span class="glyphicon glyphicon-log-out"></span>
									Cerrar Sesion</a>
							</li>
						</ul>
					</div>
				</nav> 
			</div>
            

			<hr>
			


