<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8">
		<title>Monteria Opina</title>
		<link rel="stylesheet" href="resource/css/bootstrap.min.css">
        <link rel="stylesheet" href="resource/css/estilos.css">
        <script src="resource/js/jquery-2.2.3.min.js"></script>
          <script src="resource/js/jquery-3.1.1.min.js" type="text/javascript" charset="utf-8" ></script>
          <script src="resource/js/bootstrap.min.js" type="text/javascript" charset="utf-8" ></script>

		
	</head>
	<body>
		<div class="container">
		
			<div class="row">
				<div class="col-md-4"></div>
				<div class="col-md-4">
					<img src="resource/img/logo.png"  class="img-responsive">
				</div>
				<div class="col-md-4"></div>
			</div>
			<div class="row">
				<nav  class="navbar navbar-custom" role="navigation" role="navigation">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
							<span class="sr-only">Cambiar Navegacion</span>
						</button>
						<a href="#" class="navbar-brand">MonteriaOpina</a>
					</div>
					<div class="collapse navbar-collapse navbar-ex1-collapse">
						<ul class="nav navbar-nav">
							<li>
								<a  href="/monteriaOpina?c=Usuario">
									<span class="glyphicon glyphicon-home"></span>
									<span>Home</span>
								</a>
							</li>
							<li>
								<a href="?c=Proyecto&a=Opinar">
									<span class="glyphicon glyphicon-user"></span>
									<span>Opinar</span>
								</a>
							</li>

							<li>
								<a href="?c=Proyecto&a=consultaCertificados">
									<span class="glyphicon glyphicon-cloud"></span>
									<span>Consultar datos de Certificados Unicordoba</span>
								</a>
							</li>
							
							

							<li>
								<a href="?c=Proyecto&a=GraficaCertificados">
									<span class="glyphicon glyphicon-stats"></span>
									<span>Consultar datos de DevMaster</span>
								</a>
							</li>
						
							<li>
								<a href="?c=Usuario&a=Logout">
									<span class="glyphicon glyphicon-log-out"></span>
									Cerrar Sesion</a>
							</li>
						</ul>
					</div>
				</nav> 
			</div>
            

			<hr>
			


