

<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8">
		<title>Monteria Opina</title>
		<link rel="stylesheet" href="resource/css/bootstrap.min.css">
        <link rel="stylesheet" href="resource/css/bootstrap-theme.css">
        <link rel="stylesheet" href="resource/css/bootstrap-theme.css.map">
        <link rel="stylesheet" href="resource/css/bootstrap-theme.css">
        <link rel="stylesheet" href="resource/js/jquery-ui/jquery-ui.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.3.5/css/fileinput.css" />

        


       

		
	</head>
	<body>
		<div class="container">





            <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Registro de Proyectos</div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="?c=Proyecto&a=HomeEdil">Home</a></div>
                    </div>     

                    <div style="padding-top:30px" class="panel-body" >



                    <div class="panel-body" >
                            <form id="signupform" class="form-horizontal" role="form" action="?c=Proyecto&a=Guardar" method="POST"  enctype="multipart/form-data">
                                
                            
                                    
                                
                                  
                                <div class="form-group">
                                    <label for="nombre" class="col-md-3 control-label">Titulo</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control"  value="<?php echo $proyecto->titulo; ?>" name="titulo" placeholder="Ingrese un titulo">
                                    </div>
                                </div>
                                    
                                <div class="form-group">
                                    <label for="descripcion" class="col-md-3 control-label">Descripcion</label>
                                    <div class="col-md-9">
                                      <textarea name="descripcion" class="form-control"  placeholder="Ingrese una descripcion"><?php echo $proyecto->descripcion; ?></textarea>  
                                    </div>
                                </div>

                               

                                <div class="form-group">
                                <label for="fecha_inicio" class="col-md-3 control-label">Fecha de Inicio</label>
                                <div class="col-md-9">
                                <input readonly type="text" name="fecha_inicio" value="<?php echo $proyecto->fecha_inicio; ?>" class="form-control datepicker" placeholder="Ingrese su fecha de Inicio" data-validacion-tipo="requerido" />
                                </div>
                                </div>

                                 <div class="form-group">
                                <label for="fecha_terminacion" class="col-md-3 control-label">Fecha de Terminacion</label>
                                <div class="col-md-9">
                                <input readonly type="text" name="fecha_terminacion" value="<?php echo $proyecto->fecha_terminacion; ?>" class="form-control datepicker" placeholder="Ingrese su fecha de Terminacion" data-validacion-tipo="requerido" />
                                </div>
                                </div>

                              
                                <div class="form-group">
                                    <label for="password" class="col-md-3 control-label">PDF</label>
                                    <div class="col-md-9">
                                        <input type="file" placeholder="<?php echo $proyecto->nombre_archivo; ?>" class="file" name="archivo"> <?php echo $proyecto->nombre_archivo; ?>
                                    </div>
                                </div>

                               
                            

                                <div class="form-group">
                                    <!-- Button -->                                        
                                   

                                    <div class="text-right">
                                    <button class="btn btn-success"><i class="icon-hand-right"></i> &nbsp Guardar</button>
                                    </div>
                                </div>
                                
                              
                
                                
                            </form>
                      
                        

                         </div>

                         </div>
                         </div>              
                
         
    </div>
     <script src="resource/js/jquery-2.2.3.min.js"></script>
          <script src="resource/js/jquery-3.1.1.min.js" type="text/javascript" charset="utf-8" ></script>
          <script src="resource/js/bootstrap.min.js" type="text/javascript" charset="utf-8" ></script>
           <script src="resource/js/validador.js" type="text/javascript" charset="utf-8" ></script>

        <script src="resource/js/jquery-ui/jquery-ui.min.js"></script>
        <script src="resource/js/ini.js"></script>
        <script src="resource/js/jquery.anexsoft-validator.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.3.5/js/fileinput.js"></script>
    </body>
</html>

        
    </body>
</html>