<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8">
		<title>Monteria Opina</title>
		<link rel="stylesheet" href="resource/css/bootstrap.min.css">
        <link rel="stylesheet" href="resource/css/bootstrap-theme.css">
        <link rel="stylesheet" href="resource/css/bootstrap-theme.css.map">
        <link rel="stylesheet" href="resource/css/bootstrap-theme.css">
       

		
	</head>
	<body>
		<div class="container">

		

 <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Monteria Opina</div>
                    </div>     

                    <div style="padding-top:30px" class="panel-body" >


                    
                    <table class="table table-striped">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Descripcion</th>
            <th>Fecha Inicio</th>
            <th >Fecha Final</th>
      
        </tr>
    </thead>
    <tbody>
    <?php  $r=$this->model->Obtener($_GET['id']); ?>
        <tr>
            <td><?php echo $r->titulo; ?></td>
            <td><?php echo $r->descripcion; ?></td>
            <td><?php echo $r->fecha_inicio; ?></td>
            <td><?php echo $r->fecha_terminacion; ?></td>
           
        </tr>
    
    </tbody>
</table> 



                            
                        <form id="loginform" class="form-horizontal" role="form" action="?c=Proyecto&a=guardarOpinion" method="POST">
                             <div style="display:none" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <input id="login-username" type="text" value="<?php echo $_GET['id'];?>" class="form-control" name="id"  placeholder="Ingrese su opinion">                                     
                                    </div>


                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <textarea id="login-username" type="text" class="form-control" name="opinion"  placeholder="Ingrese su opinion"> </textarea>                                      
                            </div>
                                
                           
                                    

                              

                                <div style="margin-top:10px" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                      <button id="btn-login" type="submit" class="btn btn-success">Opinar</button>
                                     
                                    </div>
                                </div>

   
                            </form>     

                               

                        </div>                     
                    </div>  
        </div>
      

               
               
                
         </div> 
    </div>
     <script src="resource/js/jquery-2.2.3.min.js"></script>
          <script src="resource/js/jquery-3.1.1.min.js" type="text/javascript" charset="utf-8" ></script>
          <script src="resource/js/bootstrap.min.js" type="text/javascript" charset="utf-8" ></script>
           <script src="resource/js/validador.js" type="text/javascript" charset="utf-8" ></script>
        
    </body>
</html>
    