            <div class="row">
                <div class="col-xs-12">
                    <hr />
                    <footer class="text-center well">
                        <p></p>
                    </footer>                
                </div>    
            </div>
        </div>

        <script src="resource/js/bootstrap.min.js"></script>
        <script src="resource/js/jquery-ui/jquery-ui.min.js"></script>
        <script src="resource/js/ini.js"></script>
        <script src="resource/js/jquery.anexsoft-validator.js"></script>
    </body>
</html>