<!DOCTYPE html>
<html lang="es">
	<head>
		<title>Hotel Cantero</title>
        
        <meta charset="utf-8" />
        
        <link rel="stylesheet" href="public/css/bootstrap.min.css" />
        <link rel="stylesheet" href="public/css/bootstrap-theme.min.css" />
        <link rel="stylesheet" href="public/js/jquery-ui/jquery-ui.min.css" />
        <link rel="stylesheet" href="public/css/style.css" />
        <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>

	</head>

    <body>
        
    <div class="container">